// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJLZeWQxx2dCA7ubhcr3G82i6GJCuXfbA',
    appId: '1:157163708733:web:24d8a122f1f9fb858ae554',
    messagingSenderId: '157163708733',
    projectId: 'chatcomreal',
    authDomain: 'chatcomreal.firebaseapp.com',
    storageBucket: 'chatcomreal.appspot.com',
    measurementId: 'G-3R5SYW8GJ5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgdxRoLi3bKYPPXWHd6qi9JpQbyWQwYH8',
    appId: '1:157163708733:android:bf7f28e597ee84b38ae554',
    messagingSenderId: '157163708733',
    projectId: 'chatcomreal',
    storageBucket: 'chatcomreal.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzkYw8sj9xtSMfGGSGKtajIh8L2fN8DQI',
    appId: '1:157163708733:ios:6c7b0c8191e3c8728ae554',
    messagingSenderId: '157163708733',
    projectId: 'chatcomreal',
    storageBucket: 'chatcomreal.appspot.com',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzkYw8sj9xtSMfGGSGKtajIh8L2fN8DQI',
    appId: '1:157163708733:ios:6c7b0c8191e3c8728ae554',
    messagingSenderId: '157163708733',
    projectId: 'chatcomreal',
    storageBucket: 'chatcomreal.appspot.com',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJLZeWQxx2dCA7ubhcr3G82i6GJCuXfbA',
    appId: '1:157163708733:web:8070b3e81c7b6c3a8ae554',
    messagingSenderId: '157163708733',
    projectId: 'chatcomreal',
    authDomain: 'chatcomreal.firebaseapp.com',
    storageBucket: 'chatcomreal.appspot.com',
    measurementId: 'G-BYX03WPS71',
  );

}